name: Deploy to Amazon ECR

on:
  push:
    branches:
      - develop
      - master
      - release/*

env:
  AWS_REGION: ${{ secrets.MY_AWS_REGION }}                 
  ECR_REPOSITORY: ${{ secrets.MY_ECR_REPOSITORY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.MY_ECS_ACCESS_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.MY_ECS_ACCESS_KEY }}
  

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: stage

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.MY_AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: all env
      run: env

    - name: Extract Git Tag
      run: echo "GIT_TAG=${GITHUB_REF_NAME##*/}-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
     
    - name: Build, tag, and push image to Amazon ECR
      env:
         working-directory: ./UI/UI
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         IMAGE_TAG: ${{ env.GIT_TAG }}
      run: |
        working-directory: ${{env.WORKING-DIRECTORY}}
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
